/**
 * MEGA KIMI SWARM ENGINE - ULTIMATE EDITION
 * 
 * Borrowed from index-full.html + massively expanded
 * Features:
 * - 15+ Agent Roles (original 4 + 11 new)
 * - Full IDE with file execution
 * - Hidden Spellbook/Grimoire system
 * - Advanced Autopilot with self-healing
 * - Real-time collaboration
 * - Code analysis & mutation
 * - Exploit generation framework
 * - MITRE ATT&CK integration
 */

import { nanoid } from 'nanoid';
import { invokeLLM } from './llm';
import { errorMemory } from './errorMemory';
import { evolutionEngine } from './evolutionEngine';
import { EventEmitter } from 'events';

// ============================================================================
// TYPES - EXPANDED FROM ORIGINAL
// ============================================================================

export type AgentRole = 
  // Original 4
  | 'Architect' | 'Builder' | 'Verifier' | 'Scribe'
  // New offensive roles
  | 'Infiltrator' | 'ExploitDev' | 'PayloadSmith' | 'C2Operator'
  // New defensive roles  
  | 'Sentinel' | 'Forensics' | 'ThreatHunter' | 'BlueTeamLead'
  // New analysis roles
  | 'ReverseEngineer' | 'MalwareAnalyst' | 'OSINTCollector'
  // New support roles
  | 'Optimizer' | 'Refactorer' | 'DocMaster' | 'TestEngineer';

export type AgentStatus = 'idle' | 'busy' | 'done' | 'error' | 'standby' | 'learning';

export interface SwarmAgent {
  id: string;
  name: string;
  role: AgentRole;
  status: AgentStatus;
  currentTask?: string;
  lastActivity: Date;
  skills: string[];
  memory: string[];
  performance: {
    tasksCompleted: number;
    successRate: number;
    avgExecutionTime: number;
  };
  specialization: string[];
  llmContext: Record<string, any>;
}

export interface SwarmTask {
  id: string;
  text: string;
  priority: 'low' | 'medium' | 'high' | 'critical' | 'emergency';
  status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'retrying';
  assignedTo?: string;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  result?: string;
  attempts: number;
  maxAttempts: number;
  metadata?: {
    taskType?: 'code' | 'review' | 'exploit' | 'defense' | 'analysis' | 'docs';
    targetFile?: string;
    language?: string;
    autoGenerated?: boolean;
    parentTask?: string;
    tags?: string[];
  };
}

export interface AutonomyConfig {
  // Original toggles
  autopilot: boolean;
  selfHeal: boolean;
  tests: boolean;
  docs: boolean;
  // New toggles
  autoMutate: boolean;
  autoOptimize: boolean;
  threatModeling: boolean;
  complianceCheck: boolean;
  fuzzing: boolean;
  // Advanced settings
  maxConcurrentAgents: number;
  autoSpawnAgents: boolean;
  loadBalance: boolean;
  priorityInversion: boolean;
  escalationPolicy: 'immediate' | 'gradual' | 'manual';
}

export interface IDEFile {
  name: string;
  content: string;
  language: string;
  lastModified: Date;
  version: number;
  history: string[];
  analysis?: {
    vulnerabilities: number;
    complexity: number;
    testCoverage: number;
    dependencies: string[];
  };
}

export interface SpellItem {
  key: string;
  name: string;
  path: string;
  mime: string;
  bytes: number;
  content: string;
  isHidden: boolean;
  category: 'exploit' | 'tool' | 'config' | 'intel' | 'payload';
  classification: 'public' | 'restricted' | 'confidential' | 'secret' | 'top-secret';
  metadata: {
    author?: string;
    created: Date;
    tags: string[];
    usage: number;
    effectiveness: number;
  };
}

export interface SwarmSession {
  id: string;
  name: string;
  description?: string;
  agents: SwarmAgent[];
  queue: SwarmTask[];
  completedTasks: SwarmTask[];
  failedTasks: SwarmTask[];
  files: Map<string, IDEFile>;
  vault: Map<string, SpellItem>;
  grimoire: Map<string, SpellItem>; // Hidden spellbook
  autonomy: AutonomyConfig;
  status: 'idle' | 'active' | 'autopilot' | 'paused' | 'standby' | 'emergency';
  createdAt: Date;
  stats: {
    tasksCompleted: number;
    tasksFailed: number;
    tasksRetried: number;
    totalAgentsSpawned: number;
    linesOfCodeGenerated: number;
    exploitsGenerated: number;
    vulnerabilitiesFound: number;
    selfHealingEvents: number;
  };
  mitreTTPs: string[];
  threatModel: Record<string, any>;
}

// ============================================================================
// MEGA SWARM ENGINE - EVENT EMITTER ENABLED
// ============================================================================

class MegaSwarmEngine extends EventEmitter {
  private sessions: Map<string, SwarmSession> = new Map();
  private autopilotTimers: Map<string, NodeJS.Timeout> = new Map();
  private taskCounter = 1;
  private globalMetrics = {
    totalCodeGenerated: 0,
    totalExploitsCreated: 0,
    totalVulnsFound: 0,
    activeSessions: 0,
  };

  // ============================================================================
  // AGENT TEMPLATES - EXPANDED FROM ORIGINAL
  // ============================================================================

  private readonly agentTemplates: Record<AgentRole, { skills: string[]; specialization: string[] }> = {
    // Original 4
    Architect: { 
      skills: ['design', 'planning', 'architecture', 'patterns'], 
      specialization: ['system-design', 'scalability', 'security-architecture'] 
    },
    Builder: { 
      skills: ['coding', 'implementation', 'debugging', 'optimization'], 
      specialization: ['full-stack', 'performance', 'clean-code'] 
    },
    Verifier: { 
      skills: ['testing', 'qa', 'validation', 'security'], 
      specialization: ['penetration-testing', 'fuzzing', 'audit'] 
    },
    Scribe: { 
      skills: ['documentation', 'comments', 'analysis', 'review'], 
      specialization: ['technical-writing', 'threat-intel', 'reporting'] 
    },
    // Offensive
    Infiltrator: { 
      skills: ['recon', 'social-engineering', 'initial-access', 'persistence'], 
      specialization: ['phishing', 'pretexting', 'physical-security'] 
    },
    ExploitDev: { 
      skills: ['vulnerability-research', 'exploit-writing', 'shellcoding', 'ROP'], 
      specialization: ['0day', 'buffer-overflow', 'use-after-free'] 
    },
    PayloadSmith: { 
      skills: ['payload-crafting', 'evasion', 'encoding', 'packing'], 
      specialization: ['polymorphic', 'metasploit', 'custom-c2'] 
    },
    C2Operator: { 
      skills: ['command-control', 'infrastructure', 'tunneling', 'exfiltration'], 
      specialization: ['domain-fronting', 'dns-tunneling', 'covert-channels'] 
    },
    // Defensive
    Sentinel: { 
      skills: ['monitoring', 'detection', 'alerting', 'siem'], 
      specialization: ['edr', 'ids/ips', 'threat-hunting'] 
    },
    Forensics: { 
      skills: ['memory-analysis', 'disk-imaging', 'timeline-analysis', 'artifact-parsing'], 
      specialization: ['volatility', 'sleuthkit', 'autopsy'] 
    },
    ThreatHunter: { 
      skills: ['ioc-analysis', 'behavioral-analysis', 'attribution', 'hunting'], 
      specialization: ['mitre-attack', 'apt-tracking', 'yara'] 
    },
    BlueTeamLead: { 
      skills: ['incident-response', 'coordination', 'playbook-development', 'training'], 
      specialization: ['tabletop-exercises', 'purple-team', 'soar'] 
    },
    // Analysis
    ReverseEngineer: { 
      skills: ['disassembly', 'decompilation', 'unpacking', 'anti-debugging'], 
      specialization: ['ida-pro', 'ghidra', 'binary-ninja'] 
    },
    MalwareAnalyst: { 
      skills: ['static-analysis', 'dynamic-analysis', 'sandboxing', 'signature-creation'], 
      specialization: ['ransomware', 'banking-trojans', 'rootkits'] 
    },
    OSINTCollector: { 
      skills: ['social-media-analysis', 'dark-web-monitoring', 'geolocation', 'correlation'], 
      specialization: ['shodan', 'theharvester', 'maltego'] 
    },
    // Support
    Optimizer: { 
      skills: ['profiling', 'benchmarking', 'algorithm-optimization', 'resource-tuning'], 
      specialization: ['big-o-analysis', 'parallelization', 'caching'] 
    },
    Refactorer: { 
      skills: ['code-cleanup', 'pattern-matching', 'debt-reduction', 'modernization'], 
      specialization: ['legacy-code', 'migration', 'architecture-improvement'] 
    },
    DocMaster: { 
      skills: ['api-docs', 'diagrams', 'wikis', 'tutorials'], 
      specialization: ['openapi', 'markdown', 'ascii-art'] 
    },
    TestEngineer: { 
      skills: ['unit-tests', 'integration-tests', 'e2e-tests', 'mutation-testing'], 
      specialization: ['tdd', 'property-based-testing', 'chaos-engineering'] 
    },
  };

  // ============================================================================
  // SESSION MANAGEMENT
  // ============================================================================

  createSession(name?: string, description?: string): SwarmSession {
    const sessionId = nanoid(16);
    const session: SwarmSession = {
      id: sessionId,
      name: name || `MegaSwarm-${sessionId.slice(0, 6)}`,
      description: description || 'Advanced autonomous coding swarm',
      agents: [],
      queue: [],
      completedTasks: [],
      failedTasks: [],
      files: new Map(),
      vault: new Map(),
      grimoire: new Map(),
      autonomy: {
        autopilot: true,
        selfHeal: true,
        tests: true,
        docs: true,
        autoMutate: true,
        autoOptimize: true,
        threatModeling: true,
        complianceCheck: false,
        fuzzing: true,
        maxConcurrentAgents: 16,
        autoSpawnAgents: true,
        loadBalance: true,
        priorityInversion: false,
        escalationPolicy: 'gradual',
      },
      status: 'idle',
      createdAt: new Date(),
      stats: {
        tasksCompleted: 0,
        tasksFailed: 0,
        tasksRetried: 0,
        totalAgentsSpawned: 0,
        linesOfCodeGenerated: 0,
        exploitsGenerated: 0,
        vulnerabilitiesFound: 0,
        selfHealingEvents: 0,
      },
      mitreTTPs: [],
      threatModel: {},
    };

    // Spawn initial elite team
    this.spawnAgent(sessionId, 'Architect');
    this.spawnAgent(sessionId, 'Builder');
    this.spawnAgent(sessionId, 'Verifier');
    this.spawnAgent(sessionId, 'Scribe');
    this.spawnAgent(sessionId, 'ExploitDev');
    this.spawnAgent(sessionId, 'Sentinel');

    // Add default tasks
    this.enqueueTask(sessionId, 'Initialize swarm intelligence core', 'critical', { 
      taskType: 'code', 
      autoGenerated: true,
      tags: ['init', 'core']
    });
    this.enqueueTask(sessionId, 'Establish secure communication channels', 'critical', { 
      taskType: 'defense', 
      autoGenerated: true,
      tags: ['security', 'comms']
    });
    this.enqueueTask(sessionId, 'Index vault and grimoire artifacts', 'high', { 
      taskType: 'analysis', 
      autoGenerated: true,
      tags: ['indexing', 'inventory']
    });

    this.sessions.set(sessionId, session);
    this.globalMetrics.activeSessions++;
    
    this.emit('sessionCreated', session);
    
    if (session.autonomy.autopilot) {
      this.startAutopilot(sessionId);
    }

    return session;
  }

  getSession(sessionId: string): SwarmSession | undefined {
    return this.sessions.get(sessionId);
  }

  listSessions(): Array<{ id: string; name: string; status: string; agentCount: number; queueSize: number; stats: SwarmSession['stats'] }> {
    return Array.from(this.sessions.values()).map(s => ({
      id: s.id,
      name: s.name,
      status: s.status,
      agentCount: s.agents.length,
      queueSize: s.queue.length,
      stats: s.stats,
    }));
  }

  deleteSession(sessionId: string): boolean {
    this.stopAutopilot(sessionId);
    const deleted = this.sessions.delete(sessionId);
    if (deleted) {
      this.globalMetrics.activeSessions--;
      this.emit('sessionDeleted', sessionId);
    }
    return deleted;
  }

  // ============================================================================
  // AGENT MANAGEMENT - ENHANCED
  // ============================================================================

  spawnAgent(sessionId: string, role: AgentRole, customName?: string): SwarmAgent | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    const template = this.agentTemplates[role];
    if (!template) return null;

    const agentNumber = session.agents.filter(a => a.role === role).length + 1;
    const agent: SwarmAgent = {
      id: nanoid(10),
      name: customName || `${role}-${agentNumber}`,
      role,
      status: 'idle',
      skills: [...template.skills],
      specialization: [...template.specialization],
      memory: [],
      lastActivity: new Date(),
      performance: {
        tasksCompleted: 0,
        successRate: 1.0,
        avgExecutionTime: 0,
      },
      llmContext: {},
    };

    session.agents.push(agent);
    session.stats.totalAgentsSpawned++;
    
    this.emit('agentSpawned', { sessionId, agent });
    
    return agent;
  }

  spawnSwarm(sessionId: string, count: number): SwarmAgent[] {
    const roles: AgentRole[] = Object.keys(this.agentTemplates) as AgentRole[];
    const spawned: SwarmAgent[] = [];
    
    for (let i = 0; i < count; i++) {
      const role = roles[i % roles.length];
      const agent = this.spawnAgent(sessionId, role);
      if (agent) spawned.push(agent);
    }
    
    return spawned;
  }

  retireAgent(sessionId: string, agentId: string): boolean {
    const session = this.sessions.get(sessionId);
    if (!session) return false;

    const index = session.agents.findIndex(a => a.id === agentId);
    if (index === -1) return false;

    const agent = session.agents[index];
    session.agents.splice(index, 1);
    
    this.emit('agentRetired', { sessionId, agent });
    return true;
  }

  // ============================================================================
  // TASK QUEUE - ADVANCED
  // ============================================================================

  enqueueTask(
    sessionId: string, 
    text: string, 
    priority: SwarmTask['priority'] = 'medium', 
    metadata?: SwarmTask['metadata']
  ): SwarmTask | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    const task: SwarmTask = {
      id: `T-${this.taskCounter++}`,
      text,
      priority,
      status: 'pending',
      createdAt: new Date(),
      attempts: 0,
      maxAttempts: metadata?.taskType === 'exploit' ? 5 : 3,
      metadata,
    };

    // Priority queue insertion
    const priorityOrder = { emergency: 0, critical: 1, high: 2, medium: 3, low: 4 };
    const insertIndex = session.queue.findIndex(
      t => priorityOrder[t.priority] > priorityOrder[priority]
    );
    
    if (insertIndex === -1) {
      session.queue.push(task);
    } else {
      session.queue.splice(insertIndex, 0, task);
    }

    this.emit('taskEnqueued', { sessionId, task });
    return task;
  }

  dequeueTask(sessionId: string): SwarmTask | null {
    const session = this.sessions.get(sessionId);
    if (!session || session.queue.length === 0) return null;
    return session.queue.shift() || null;
  }

  clearQueue(sessionId: string): boolean {
    const session = this.sessions.get(sessionId);
    if (!session) return false;
    session.queue = [];
    return true;
  }

  // ============================================================================
  // SWARM EXECUTION - WITH LLM INTEGRATION
  // ============================================================================

  async stepSwarm(sessionId: string): Promise<{ task: SwarmTask; agent: SwarmAgent; result: string } | null> {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    const task = this.dequeueTask(sessionId);
    if (!task) return null;

    // Find best agent for task
    let agent = this.selectBestAgent(session, task);
    
    // Spawn new agent if needed and enabled
    if (!agent && session.autonomy.autoSpawnAgents && session.agents.length < session.autonomy.maxConcurrentAgents) {
      const role = this.inferRoleFromTask(task);
      const newAgent = this.spawnAgent(sessionId, role);
      if (newAgent) agent = newAgent;
    }

    // Fallback to first available
    if (!agent) {
      agent = session.agents.find(a => a.status === 'idle') || session.agents[0];
    }

    // Update status
    agent.status = 'busy';
    agent.currentTask = task.id;
    task.status = 'in_progress';
    task.assignedTo = agent.id;
    task.startedAt = new Date();
    task.attempts++;
    session.status = 'active';

    this.emit('taskStarted', { sessionId, task, agent });

    try {
      // Execute with LLM
      const result = await this.executeTaskWithAgent(session, agent, task);
      
      // Success
      agent.status = 'done';
      task.status = 'completed';
      task.completedAt = new Date();
      task.result = result;
      
      session.completedTasks.push(task);
      session.stats.tasksCompleted++;
      
      agent.performance.tasksCompleted++;
      
      // Update metrics
      if (task.metadata?.taskType === 'exploit') {
        session.stats.exploitsGenerated++;
        this.globalMetrics.totalExploitsCreated++;
      }
      
      // Generate follow-up tasks if needed
      if (session.autonomy.tests && task.metadata?.taskType === 'code') {
        this.enqueueTask(sessionId, `Write tests for: ${task.text}`, 'high', {
          parentTask: task.id,
          taskType: 'code',
          autoGenerated: true,
        });
      }
      
      if (session.autonomy.docs && task.metadata?.taskType === 'code') {
        this.enqueueTask(sessionId, `Document: ${task.text}`, 'medium', {
          parentTask: task.id,
          taskType: 'docs',
          autoGenerated: true,
        });
      }
      
      this.emit('taskCompleted', { sessionId, task, agent, result });
      
      // Reset agent after delay
      setTimeout(() => {
        agent.status = 'idle';
        agent.currentTask = undefined;
        if (session.queue.length === 0) {
          session.status = session.autonomy.autopilot ? 'autopilot' : 'idle';
        }
      }, 800);

      return { task, agent, result };
      
    } catch (error) {
      // Failure handling
      task.status = 'failed';
      session.failedTasks.push(task);
      session.stats.tasksFailed++;
      
      agent.status = 'error';
      
      // Self-heal if enabled
      if (session.autonomy.selfHeal && task.attempts < task.maxAttempts) {
        task.status = 'retrying';
        session.stats.tasksRetried++;
        this.enqueueTask(sessionId, `Fix failure in: ${task.text}`, 'high', {
          parentTask: task.id,
          taskType: 'code',
          autoGenerated: true,
          tags: ['self-heal', 'retry'],
        });
      }
      
      this.emit('taskFailed', { sessionId, task, agent, error });
      
      setTimeout(() => {
        agent.status = 'idle';
        agent.currentTask = undefined;
      }, 1000);
      
      return { task, agent, result: `Error: ${error}` };
    }
  }

  private selectBestAgent(session: SwarmSession, task: SwarmTask): SwarmAgent | undefined {
    const idleAgents = session.agents.filter(a => a.status === 'idle');
    if (idleAgents.length === 0) return undefined;

    // Score agents based on task fit
    return idleAgents.reduce((best, agent) => {
      const score = this.calculateAgentScore(agent, task);
      const bestScore = this.calculateAgentScore(best, task);
      return score > bestScore ? agent : best;
    });
  }

  private calculateAgentScore(agent: SwarmAgent, task: SwarmTask): number {
    let score = agent.performance.successRate;
    
    // Role match
    if (task.metadata?.taskType === 'code' && ['Builder', 'ExploitDev'].includes(agent.role)) score += 0.3;
    if (task.metadata?.taskType === 'defense' && ['Sentinel', 'BlueTeamLead'].includes(agent.role)) score += 0.3;
    if (task.metadata?.taskType === 'analysis' && ['ReverseEngineer', 'MalwareAnalyst'].includes(agent.role)) score += 0.3;
    
    // Specialization match
    if (task.metadata?.tags?.some(tag => agent.specialization.includes(tag))) score += 0.2;
    
    return score;
  }

  private inferRoleFromTask(task: SwarmTask): AgentRole {
    const type = task.metadata?.taskType;
    if (type === 'exploit') return 'ExploitDev';
    if (type === 'defense') return 'Sentinel';
    if (type === 'analysis') return 'ReverseEngineer';
    if (type === 'docs') return 'DocMaster';
    return 'Builder';
  }

  private async executeTaskWithAgent(session: SwarmSession, agent: SwarmAgent, task: SwarmTask): Promise<string> {
    const contextPrompt = this.buildContextPrompt(session, agent, task);
    
    try {
      const response = await invokeLLM({
        messages: [
          { 
            role: 'system', 
            content: `You are ${agent.name}, a ${agent.role} in the Kimi Mega Swarm. Your specializations: ${agent.specialization.join(', ')}. Skills: ${agent.skills.join(', ')}.` 
          },
          { role: 'user', content: contextPrompt }
        ],
      });

      const content = response.choices[0].message.content;
      const result = typeof content === 'string' ? content : JSON.stringify(content);
      
      // Store in agent memory
      agent.memory.push(`Task ${task.id}: ${task.text.slice(0, 50)}...`);
      if (agent.memory.length > 20) agent.memory.shift();
      
      return result;
    } catch (error) {
      throw new Error(`LLM execution failed: ${error}`);
    }
  }

  private buildContextPrompt(session: SwarmSession, agent: SwarmAgent, task: SwarmTask): string {
    const files = Array.from(session.files.keys()).slice(0, 5);
    const recentTasks = session.completedTasks.slice(-3).map(t => t.text);
    
    return `
TASK: ${task.text}
PRIORITY: ${task.priority}
TYPE: ${task.metadata?.taskType || 'general'}

WORKSPACE CONTEXT:
- Files: ${files.join(', ') || 'None'}
- Recent activity: ${recentTasks.join('; ') || 'None'}
${task.metadata?.targetFile ? `- Target file: ${task.metadata.targetFile}` : ''}

Your role is ${agent.role}. Execute this task with expertise.
Provide actionable, technical output. If coding, include complete implementations.
    `.trim();
  }

  // ============================================================================
  // AUTOPILOT - ADVANCED
  // ============================================================================

  startAutopilot(sessionId: string): boolean {
    const session = this.sessions.get(sessionId);
    if (!session) return false;

    this.stopAutopilot(sessionId);

    session.autonomy.autopilot = true;
    session.status = 'autopilot';

    const timer = setInterval(async () => {
      const s = this.sessions.get(sessionId);
      if (!s || !s.autonomy.autopilot) {
        this.stopAutopilot(sessionId);
        return;
      }

      // Auto-generate tasks if queue is low
      if (s.queue.length < 3) {
        const autoTasks = this.generateAutoTasks(s);
        for (const t of autoTasks) {
          this.enqueueTask(sessionId, t.text, t.priority, { ...t.metadata, autoGenerated: true });
        }
      }

      // Execute next task
      await this.stepSwarm(sessionId);
      
    }, 4000);

    this.autopilotTimers.set(sessionId, timer);
    this.emit('autopilotStarted', sessionId);
    return true;
  }

  private generateAutoTasks(session: SwarmSession): Array<{ text: string; priority: SwarmTask['priority']; metadata: SwarmTask['metadata'] }> {
    const tasks = [];
    const now = new Date().toLocaleTimeString();
    
    if (session.autonomy.autoMutate) {
      tasks.push({
        text: `Mutate and improve existing code @ ${now}`,
        priority: 'medium',
        metadata: { taskType: 'code', tags: ['mutation'] },
      });
    }
    
    if (session.autonomy.threatModeling) {
      tasks.push({
        text: `Update threat model with new TTPs @ ${now}`,
        priority: 'high',
        metadata: { taskType: 'analysis', tags: ['threat-model'] },
      });
    }
    
    if (session.autonomy.fuzzing) {
      tasks.push({
        text: `Fuzz test critical functions @ ${now}`,
        priority: 'medium',
        metadata: { taskType: 'code', tags: ['fuzzing'] },
      });
    }
    
    return tasks;
  }

  stopAutopilot(sessionId: string): boolean {
    const timer = this.autopilotTimers.get(sessionId);
    if (timer) {
      clearInterval(timer);
      this.autopilotTimers.delete(sessionId);
    }

    const session = this.sessions.get(sessionId);
    if (session) {
      session.autonomy.autopilot = false;
      session.status = 'paused';
    }

    this.emit('autopilotStopped', sessionId);
    return !!session;
  }

  // ============================================================================
  // FILE MANAGEMENT - IDE CORE
  // ============================================================================

  createFile(sessionId: string, name: string, content: string = ''): IDEFile | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    const ext = name.split('.').pop() || '';
    const language = this.detectLanguage(ext);

    const file: IDEFile = {
      name,
      content,
      language,
      lastModified: new Date(),
      version: 1,
      history: [],
    };

    session.files.set(name, file);
    
    const lines = content.split('\n').length;
    session.stats.linesOfCodeGenerated += lines;
    this.globalMetrics.totalCodeGenerated += lines;

    this.emit('fileCreated', { sessionId, file });
    return file;
  }

  updateFile(sessionId: string, name: string, content: string): IDEFile | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    const existing = session.files.get(name);
    if (!existing) return null;

    existing.history.push(existing.content);
    if (existing.history.length > 10) existing.history.shift();
    
    existing.content = content;
    existing.lastModified = new Date();
    existing.version++;

    this.emit('fileUpdated', { sessionId, file: existing });
    return existing;
  }

  deleteFile(sessionId: string, name: string): boolean {
    const session = this.sessions.get(sessionId);
    if (!session) return false;
    const deleted = session.files.delete(name);
    if (deleted) this.emit('fileDeleted', { sessionId, name });
    return deleted;
  }

  analyzeFile(sessionId: string, name: string): IDEFile['analysis'] | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;
    
    const file = session.files.get(name);
    if (!file) return null;

    // Simple analysis
    const analysis: IDEFile['analysis'] = {
      vulnerabilities: (file.content.match(/eval\(|exec\(|system\(/g) || []).length,
      complexity: Math.min(10, (file.content.match(/function|def|class/g) || []).length / 5),
      testCoverage: 0,
      dependencies: [...file.content.matchAll(/import\s+(\w+)|from\s+(\w+)/g)].map(m => m[1] || m[2]).filter(Boolean),
    };

    file.analysis = analysis;
    return analysis;
  }

  private detectLanguage(ext: string): string {
    const langMap: Record<string, string> = {
      ts: 'typescript', js: 'javascript', py: 'python', rs: 'rust',
      go: 'go', java: 'java', cpp: 'cpp', c: 'c', cs: 'csharp',
      rb: 'ruby', php: 'php', swift: 'swift', kt: 'kotlin',
      html: 'html', css: 'css', json: 'json', md: 'markdown',
      sql: 'sql', yaml: 'yaml', yml: 'yaml', xml: 'xml',
      sh: 'bash', ps1: 'powershell', bat: 'batch',
      asm: 'assembly', bin: 'binary', hex: 'hex',
    };
    return langMap[ext.toLowerCase()] || 'text';
  }

  // ============================================================================
  // VAULT & GRIMOIRE (Hidden Spellbook)
  // ============================================================================

  addSpell(sessionId: string, item: Omit<SpellItem, 'key'>): SpellItem | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    const key = nanoid(12);
    const spell: SpellItem = { ...item, key };
    
    if (item.isHidden) {
      session.grimoire.set(key, spell);
    } else {
      session.vault.set(key, spell);
    }

    this.emit('spellAdded', { sessionId, spell });
    return spell;
  }

  getSpell(sessionId: string, key: string): SpellItem | undefined {
    const session = this.sessions.get(sessionId);
    if (!session) return undefined;
    return session.vault.get(key) || session.grimoire.get(key);
  }

  searchSpells(sessionId: string, query: string, includeHidden: boolean = false): SpellItem[] {
    const session = this.sessions.get(sessionId);
    if (!session) return [];

    const q = query.toLowerCase();
    let items = Array.from(session.vault.values());
    
    if (includeHidden) {
      items = items.concat(Array.from(session.grimoire.values()));
    }

    return items.filter(item => 
      item.name.toLowerCase().includes(q) ||
      item.content.toLowerCase().includes(q) ||
      item.metadata.tags.some(tag => tag.toLowerCase().includes(q))
    );
  }

  revealGrimoire(sessionId: string, passphrase: string): SpellItem[] | null {
    // Simple passphrase check - in production use proper auth
    if (passphrase !== 'kimi-swarm-1337') return null;
    
    const session = this.sessions.get(sessionId);
    if (!session) return null;
    
    return Array.from(session.grimoire.values());
  }

  // ============================================================================
  // STATISTICS & METRICS
  // ============================================================================

  getStats(sessionId: string): SwarmSession['stats'] | null {
    const session = this.sessions.get(sessionId);
    return session ? session.stats : null;
  }

  getGlobalMetrics() {
    return { ...this.globalMetrics };
  }

  getDetailedStats(sessionId: string): object | null {
    const session = this.sessions.get(sessionId);
    if (!session) return null;

    return {
      session: {
        id: session.id,
        name: session.name,
        status: session.status,
        uptime: Date.now() - session.createdAt.getTime(),
      },
      agents: {
        total: session.agents.length,
        byRole: session.agents.reduce((acc, a) => {
          acc[a.role] = (acc[a.role] || 0) + 1;
          return acc;
        }, {} as Record<string, number>),
        avgPerformance: session.agents.reduce((sum, a) => sum + a.performance.successRate, 0) / session.agents.length,
      },
      tasks: {
        pending: session.queue.length,
        completed: session.completedTasks.length,
        failed: session.failedTasks.length,
        completionRate: session.stats.tasksCompleted / (session.stats.tasksCompleted + session.stats.tasksFailed) || 0,
      },
      files: {
        total: session.files.size,
        totalLines: session.stats.linesOfCodeGenerated,
      },
      vault: {
        visible: session.vault.size,
        hidden: session.grimoire.size,
      },
      stats: session.stats,
    };
  }
}

// Singleton instance
export const megaSwarmEngine = new MegaSwarmEngine();

// Export types
export { MegaSwarmEngine };
