export const AVAILABLE_MODELS = [
  { id: "gpt-4.1-mini", name: "GPT-4.1 Mini", provider: "OpenAI" },
  { id: "gpt-4o", name: "GPT-4o", provider: "OpenAI" },
  { id: "claude-3.5-sonnet", name: "Claude 3.5 Sonnet", provider: "Anthropic" },
  { id: "claude-3-opus", name: "Claude 3 Opus", provider: "Anthropic" },
  { id: "claude-3-haiku", name: "Claude 3 Haiku", provider: "Anthropic" },
  { id: "gpt-4-turbo", name: "GPT-4 Turbo", provider: "OpenAI" },
  { id: "gpt-4", name: "GPT-4", provider: "OpenAI" },
  { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo", provider: "OpenAI" },
  { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro", provider: "Google" },
  { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash", provider: "Google" },
  { id: "llama-3.1-405b", name: "Llama 3.1 405B", provider: "Meta" },
  { id: "llama-3.1-70b", name: "Llama 3.1 70B", provider: "Meta" },
  { id: "llama-3.1-8b", name: "Llama 3.1 8B", provider: "Meta" },
  { id: "mistral-large", name: "Mistral Large", provider: "Mistral AI" },
  { id: "mistral-medium", name: "Mistral Medium", provider: "Mistral AI" },
  { id: "mistral-small", name: "Mistral Small", provider: "Mistral AI" },
  { id: "mixtral-8x7b", name: "Mixtral 8x7B", provider: "Mistral AI" },
  { id: "mixtral-8x22b", name: "Mixtral 8x22B", provider: "Mistral AI" },
  { id: "command-r-plus", name: "Command R+", provider: "Cohere" },
  { id: "command-r", name: "Command R", provider: "Cohere" },
  { id: "grok-2", name: "Grok 2", provider: "xAI" },
  { id: "grok-1.5", name: "Grok 1.5", provider: "xAI" },
  { id: "deepseek-v2", name: "DeepSeek V2", provider: "DeepSeek" },
  { id: "deepseek-coder", name: "DeepSeek Coder", provider: "DeepSeek" },
  { id: "qwen-2.5-72b", name: "Qwen 2.5 72B", provider: "Alibaba" },
  { id: "qwen-2.5-32b", name: "Qwen 2.5 32B", provider: "Alibaba" },
  { id: "yi-34b", name: "Yi 34B", provider: "01.AI" },
  { id: "phi-3-medium", name: "Phi-3 Medium", provider: "Microsoft" },
  { id: "phi-3-small", name: "Phi-3 Small", provider: "Microsoft" },
  { id: "nemotron-70b", name: "Nemotron 70B", provider: "NVIDIA" },
  { id: "falcon-180b", name: "Falcon 180B", provider: "TII" },
  { id: "vicuna-33b", name: "Vicuna 33B", provider: "LMSYS" },
  { id: "wizardlm-70b", name: "WizardLM 70B", provider: "WizardLM" },
  { id: "orca-2", name: "Orca 2", provider: "Microsoft" },
  { id: "starling-7b", name: "Starling 7B", provider: "Berkeley" },
  { id: "zephyr-7b", name: "Zephyr 7B", provider: "HuggingFace" },
  { id: "openhermes-2.5", name: "OpenHermes 2.5", provider: "Teknium" },
  { id: "nous-hermes-2", name: "Nous Hermes 2", provider: "Nous Research" },
  { id: "solar-10.7b", name: "Solar 10.7B", provider: "Upstage" },
  { id: "dolphin-2.5", name: "Dolphin 2.5", provider: "Cognitive Computations" },
  { id: "codellama-70b", name: "CodeLlama 70B", provider: "Meta" },
  { id: "phind-codellama", name: "Phind CodeLlama", provider: "Phind" },
];
